### ISSUE TITLE
NumberFormatException when using conversations.history

### ISSUE THREAD

**Issue by rasharab** [slackapi/java-slack-sdk#1397]
We are hitting this error when calling conversations.history
Not sure how video_html_height is a double, but your sdk treats it as an Integer.
This looks more like a server side bug but you guys would know better who to reach out to...

> Got an exception while calling conversations.history API (team: ******, error: java.lang.NumberFormatException: Expected an int but was 266.38917793965 at line 1 column 51910 path $.messages[113].attachments[0].video_html_height)

```
 j.l.NumberFormatException: Expected an int but was 266.38917793965 at line 1 column 51910 path $.messages[113].attachments[0].video_html_height
	at c.g.g.s.JsonReader.nextInt(JsonReader.java:1218)
	at c.g.g.i.b.TypeAdapters$7.read(TypeAdapters.java:249)
	... 31 common frames omitted
Wrapped by: c.g.g.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 266.38917793965 at line 1 column 51910 path $.messages[113].attachments[0].video_html_height
	at c.g.g.i.b.TypeAdapters$7.read(TypeAdapters.java:251)
	at c.g.g.i.b.TypeAdapters$7.read(TypeAdapters.java:241)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
	at c.g.g.i.b.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
	at c.g.g.i.b.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapte...

```
#### The Slack SDK version

1.44.4

**Comment by seratch** [comment]
Thank you so much for reporting this. It seems the server now returns either double or integer value for the property while it used to consistently return only integer. We will update the type to Double to prevent this runtime error.

**Comment by seratch** [comment]
The latest revision resolves this issue. Will release a new patch version shortly.
