### ISSUE TITLE
java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()

### ISSUE THREAD

**Issue by Satyaki0924** [slackapi/java-slack-sdk#313]
```
06:14:54,273 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 71) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./internetAPI: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./internetAPI: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
--
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:84)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | at org.jboss.threads.JBossThread.run(JBossThread.java:320)
  | Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
  | at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:101)
  | at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:263)
  | at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:153)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:99)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
  | ... 6 more
  | Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
  | at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpointInternal(ServerWebSocketContainer.java:660)
  | at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpoint(ServerWebSocketContainer.java:586)
  | at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:95)
  | ... 10 more
  | Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()
  | at org.jboss.as.ee.component.ReflectiveClassIntrospector.createFactory(ReflectiveClassIntrospector.java:59)
  | at org.jboss.as.ee.component.ComponentRegistry.createInstanceFactory(ComponentRegistry.java:76)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$ComponentClassIntrospector.createInstanceFactory(UndertowDeploymentInfoService.java:1287)
  | at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpointInternal(ServerWebSocketContainer.java:654)
  | ... 12 more
  | Caused by: java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()
  | at java.lang.Class.getConstructor0(Class.java:3082)
  | at java.lang.Class.getDeclaredConstructor(Class.java:2178)
  | at org.jboss.as.ee.component.ReflectiveClassIntrospector.createFactory(ReflectiveClassIntrospector.java:57)
  | ... 15 more
  |  
  | 06:14:54,469 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "internetAPI.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./internetAPI" => "java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
  | Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
  | Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
  | Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()
  | Caused by: java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()"}}
  | 06:14:54,664 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "internetAPI.war" (runtime-name : "internetAPI.war")
  | 06:14:54,666 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "jmx-metrics-adapter-ra-1.3.rar" (runtime-name : "jmx-metrics-adapter-ra-1.3.rar")
  | 06:14:54,666 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "jboss-commonj-ra-1.2.rar" (runtime-name : "jboss-commonj-ra-1.2.rar")
  | 06:14:54,667 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "activemq-rar.rar" (runtime-name : "activemq-rar.rar")
  | 06:14:54,887 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
  | WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./internetAPI: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
```

**Comment by Satyaki0924** [comment]
I am trying to deploy an application which uses jslack v 1.6.0 on Jboss EAP7.1.6 and am getting the above error. I would be thankful if anyone could share some insight on what the bug is and how to solve it.

**Comment by seratch** [comment]
@Satyaki0924 
> Caused by: java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()

It looks a binary compatibility issue. Make sure if your app depends on the same version for all jslack dependencies.

**Comment by Satyaki0924** [comment]
Thanks @seratch for the insight. For all those who is getting the same error, here is how I solved this.
**Problem:** Jboss EAP 7 websocket dependencies conflicting with jslack dependencies causing binary compatibility issue.
**Resolution:** 
Add the following dependency to your POM.xml if you are using maven
```
<dependency>
<groupId>xerces</groupId>
<artifactId>xercesImpl</artifactId>
<version>2.11.0</version>
</dependency>
```
From your standalone.xml, comment the websockets part of the subsystems
```
<servlet-container name="default">
<jsp-config />
<!--websockets /-->
</servlet-container>
```
