### ISSUE TITLE
SSL error posting to hooks.slack.com

### ISSUE THREAD

**Issue by shakismyname** [slackapi/java-slack-sdk#465]
### Issue Type

SSL error

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

We had a 4 errors last night posting to hooks.slack.com that were all SSL errors. Many of our webhooks did succeed, though, so we're perplexed what could be causing this issue. Is it a bug in the usage of okhttp, or was this a cert issue on Slack's end?

Here's a piece of the stacktrace:

```
(from an IOException)

javax.net.ssl.SSLPeerUnverifiedException: Hostname hooks.slack.com not verified (no certificates)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:384)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:325)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:197)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:233)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:107)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:75)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:74)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at com.slack.api.util.http.UserAgentInterceptor.intercept(UserAgentInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at com.slack.api.util.http.SlackHttpClient.postJsonBody(SlackHttpClient.java:99)
	at com.slack.api.Slack.send(Slack.java:105)
```

---
(only for a bug report)

The issue is reproducible in:
* Module Version: 1.0.1
* JDK Version: 11.0.1

The steps to reproduce are:
1. hit hooks.slack.com?
2. 🤞 

The expected result is:
No error

The actual result is:
SSL Error
---

### Requirements (place an `x` in each of the `[ ]`)

**TODO**:
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
This looks like the same issue with https://github.com/slackapi/java-slack-sdk/pull/452 which is an OpenJDK 11's bug.

https://travis-ci.org/github/slackapi/java-slack-sdk/jobs/686013064

```
close_Slack(test_locally.api.util.SlackHttpClientTest)  Time elapsed: 0.091 sec  <<< ERROR!
javax.net.ssl.SSLPeerUnverifiedException: Hostname slack.com not verified (no certificates)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:384)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:325)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:197)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
```

A workaround is `-Djdk.tls.client.protocols=TLSv1.2`. Or, using other Open JDK major version may help.

**Comment by shakismyname** [comment]
Oh! Didn't see that when initially searching. We'll update the package and reopen if this issue persists.

Thanks so much!
