### ISSUE TITLE
Hostname slack.com not verified (no certificates)

### ISSUE THREAD

**Issue by falkenstein** [slackapi/java-slack-sdk#482]
### Issue Type

- [x] Bug
- [ ] Enhancement / Feature request
- [x] Question
- [ ] Documentation

### Description

Hi, while using the Slack SDK with Kotlin, we've encountered a weird issue and we're honestly not 100% if it isn't on our side. When using the SDK and making Slack calls we randomly get the following:

```
Exception in thread "DefaultDispatcher-worker-1" javax.net.ssl.SSLPeerUnverifiedException: Hostname slack.com not verified (no certificates)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:384)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:325)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:197)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:235)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:74)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at com.slack.api.util.http.UserAgentInterceptor.intercept(UserAgentInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at com.slack.api.util.http.SlackHttpClient.postFormWithAuthorizationHeader(SlackHttpClient.java:93)
	at com.slack.api.util.http.SlackHttpClient.postFormWithBearerHeader(SlackHttpClient.java:88)
	at com.slack.api.methods.impl.MethodsClientImpl.runPostFormWithToken(MethodsClientImpl.java:2113)
	at com.slack.api.methods.impl.MethodsClientImpl.postFormWithTokenAndParseResponse(MethodsClientImpl.java:2197)
	at com.slack.api.methods.impl.MethodsClientImpl.conversationsOpen(MethodsClientImpl.java:1015)
	at com.slack.api.methods.impl.MethodsClientImpl.conversationsOpen(MethodsClientImpl.java:1020)
	at com.roihunter.nastenka.general.SlackManager.postFeedbackBotMessageToUser(SlackManager.kt:144)
	at com.roihunter.nastenka.flow.feedbackbot.FeedbackConnectionRequestFlow.showConnectionRequest(FeedbackConnectionRequestFlow.kt:114)
	at com.roihunter.nastenka.controller.SlackController$handleInteractiveResponse$4.invokeSuspend(SlackController.kt:112)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

The issue is random, i.e. only happens sometimes, but looks like it never happens twice in a row (that, however, can also be random). It seems to be happening with all types of requests, but unfortunately I can't confirm this, either, because of the randomness of the issue. We have encountered it for methods `chatPostMessage`, `sendViewsOpenRequest` and `viewsPublish`.

Strangely the issue only keeps showing up on our server (GCloud) and when I run the code locally on my machine. This also points to the fact that the issue might somehow be on our side (even though the error message suggests otherwise).

As it might be an issue on our side, our devops suggested a quick and dirty fix (that is imho much better than nothing): to add _insecure=true_ flag to the Slack connection. While I know it's not exactly a good practice, I would like to ask you: is this somehow even possible via the Slack SDK? I didn't find anything in the documentation (could have missed it, though).

Please, have you encountered such an issue before? Alternatively, would the aforementioned dirty fix be somewhat possible? Thanks a lot in advance!

---

Unfortunately not reproducible locally, as the issue is restricted to our server and only happens randomly.

---

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@falkenstein probably, this is the same as https://github.com/slackapi/java-slack-sdk/issues/465#issuecomment-632150000

**Comment by falkenstein** [comment]
@seratch thanks a lot for your super-fast reply :+1:  - I will try the workaround and confirm here that it worked

**Comment by seratch** [comment]
@falkenstein Let me know if you need more help here! If the workaround worked for you, could you close this issue?

**Comment by seratch** [comment]
As we don't have any further actions to take here, allow me to close this issue now. Please feel free to reopen or write in when needed.
