### ISSUE TITLE
Leaks Authorization header when new line accidentally included in token secret

### ISSUE THREAD

**Issue by AlexeiZenin** [slackapi/java-slack-sdk#566]
Please do not print the whole Authorization header in the exception thrown

#### The Slack SDK version

<dependency>
            <groupId>com.slack.api</groupId>
            <artifactId>slack-api-client</artifactId>
            <version>1.1.4</version>
</dependency>

#### Java Runtime version

OpenJDK 11

#### OS info

Linux

#### Steps to reproduce:

Set Slack token to your token value with a new line character (\n = 0x0a) at the end of it.

When trying to make a request to the API via one of the methods will error out with a stack trace which prints out the whole authorization header, thus leaking the token (which now will appear in your logging infrastructure)

#### Expected result:

Do not print out the whole Auth header to not reveal the token

#### Actual result:

`java.lang.IllegalArgumentException: Unexpected char 0x0a at 61 in Authorization value: Bearer XXXXXXXXXX`

```java
at okhttp3.Headers.checkValue(Headers.java:284) ~[okhttp-3.14.7.jar!/:na]
	at okhttp3.Headers$Builder.set(Headers.java:415) ~[okhttp-3.14.7.jar!/:na]
	at okhttp3.Request$Builder.header(Request.java:184) ~[okhttp-3.14.7.jar!/:na]
	at com.slack.api.util.http.SlackHttpClient.postFormWithAuthorizationHeader(SlackHttpClient.java:92) ~[slack-api-client-1.1.4.jar!/:1.1.4]
	at com.slack.api.util.http.SlackHttpClient.postFormWithBearerHeader(SlackHttpClient.java:88) ~[slack-api-client-1.1.4.jar!/:1.1.4]
	at com.slack.api.methods.impl.MethodsClientImpl.runPostFormWithToken(MethodsClientImpl.java:2458) ~[slack-api-client-1.1.4.jar!/:1.1.4]
	at com.slack.api.methods.impl.TeamIdCache.lambda$lookupOrResolve$0(TeamIdCache.java:33) ~[slack-api-client-1.1.4.jar!/:1.1.4]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[na:na]
	at com.slack.api.methods.impl.TeamIdCache.lookupOrResolve(TeamIdCache.java:55) ~[slack-api-client-1.1.4.jar!/:1.1.4]
	at com.slack.api.methods.impl.TeamIdCache.lookupOrResolve(TeamIdCache.java:30) ~[slack-api-client-1.1.4.jar!/:1.1.4]
	at com.slack.api.methods.impl.MethodsClientImpl.postFormWithTokenAndParseResponse(MethodsClientImpl.java:2534) ~[slack-api-client-1.1.4.jar!/:1.1.4]
	at com.slack.api.methods.impl.MethodsClientImpl.chatPostMessage(MethodsClientImpl.java:1174) ~[slack-api-client-1.1.4.jar!/:1.1.4]
```

**Comment by seratch** [comment]
@AlexeiZenin Thanks, I just confirmed this happens. I agree this should be improved. I will fix this and release a new patch version soon.
