### ISSUE TITLE
NPE in bolt-google-cloud-functions when the response body coming from Bolt app is null

### ISSUE THREAD

**Issue by Arxing** [slackapi/java-slack-sdk#836]
I use bolt-google-cloud-functions to build my slack bot. I found a bug. If the endpoint only returns context.ack(),  a NullPointerException will occur after the endpoint is executed.

The reason is that line 71 of the file SlackApiFunction.java need handle nullable response body.

#### The Slack SDK version

1.11.0

#### Java Runtime version

java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

#### OS info

Microsoft Windows [Version 10.0.19042.1165]

#### Stack Trace

```
Failed to execute com.pinkoi.toolman.features.bitrise.BitriseTokenFunction
java.lang.NullPointerException
	at java.io.Writer.write(Writer.java:157)
	at com.slack.api.bolt.google_cloud_functions.SlackApiFunction.writeResponse(SlackApiFunction.java:71)
	at com.slack.api.bolt.google_cloud_functions.SlackApiFunction.service(SlackApiFunction.java:36)
	at com.pinkoi.toolman.shared.BaseSlackApiFunction.service(BaseSlackApiFunction.kt:49)
	at com.google.cloud.functions.invoker.NewHttpFunctionExecutor.service(NewHttpFunctionExecutor.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.google.cloud.functions.invoker.runner.Invoker$NotFoundHandler.handle(Invoker.java:450)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by seratch** [comment]
Hi @Arxing, thanks for taking the time to report this issue and we are sorry about the inconvenience due to this bug. We'll fix this issue in the next version.

**Comment by seratch** [comment]
👋 Thanks again for reporting this issue. A new version (1.12.0) including the fix for this issue is now available in the Maven Central repository! Try the latest version if you have a chance 🙇
