### ISSUE TITLE
Using authRevoke() to revoke Slack OIDC token resulting in invalid_auth error

### ISSUE THREAD

**Issue by erathorus** [slackapi/java-slack-sdk#887]
### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

```
+--- com.slack.api:bolt-socket-mode:1.13.0
|    +--- com.slack.api:slack-api-model:1.13.0
|    +--- com.slack.api:slack-api-client:1.13.0
|    |    +--- com.slack.api:slack-api-model:1.13.0 (*)
|    +--- com.slack.api:slack-app-backend:1.13.0
|    |    +--- com.slack.api:slack-api-model:1.13.0 (*)
|    |    +--- com.slack.api:slack-api-client:1.13.0 (*)
|    \--- com.slack.api:bolt:1.13.0
|         +--- com.slack.api:slack-api-model:1.13.0 (*)
|         +--- com.slack.api:slack-api-client:1.13.0 (*)
|         \--- com.slack.api:slack-app-backend:1.13.0 (*)
+--- com.slack.api:bolt-socket-mode:1.13.0 (n)
```

#### Java Runtime version

```
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Corretto-11.0.12.7.2 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.12.7.2 (build 11.0.12+7-LTS, mixed mode)
```

#### OS info

```
ProductName:    macOS
ProductVersion: 11.6
BuildVersion:   20G165
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
```

#### Steps to reproduce:

The error occurs when calling `AsyncMethodsClient::authRevoke()` to revoke the OpenID Connect (OIDC) access token. The OIDC access token is granted by the [Sign In With Slack](https://api.slack.com/authentication/sign-in-with-slack) flow.

```java
var slack = new Slack();
var asyncClient = slack.methodsAsync();
asyncClient.authRevoke(req -> req.token("<slack_oidc_access_token>")).join();
```

#### Expected result:

No error occurs. I think this can be fixed either by having the SDK not calling `auth.test` for OIDC access tokens, or for Slack to support `auth.test` for OIDC access tokens.

#### Actual result:

When calling `AsyncMethodsClient::authRevoke()`, I receive the error:

```
Got an unsuccessful response from auth.test API (error: invalid_auth)
at java.lang.Thread.getStackTrace(Thread.java:1598)
    at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
    at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
    at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
    at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
    at ch.qos.logback.classic.Logger.error(Logger.java:526)
    at com.slack.api.methods.impl.TeamIdCache.lambda$lookupOrResolve$0(TeamIdCache.java:44)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
    at com.slack.api.methods.impl.TeamIdCache.lookupOrResolve(TeamIdCache.java:57)
    at com.slack.api.methods.impl.TeamIdCache.lookupOrResolve(TeamIdCache.java:30)
    at com.slack.api.methods.impl.MethodsClientImpl.postFormWithTokenAndParseResponse(MethodsClientImpl.java:3041)
    at com.slack.api.methods.impl.MethodsClientImpl.authRevoke(MethodsClientImpl.java:1107)
    at com.slack.api.methods.impl.AsyncMethodsClientImpl.lambda$authRevoke$80(AsyncMethodsClientImpl.java:1032)
    at com.slack.api.methods.impl.AsyncRateLimitExecutor.runWithoutQueue(AsyncRateLimitExecutor.java:119)
    at com.slack.api.methods.impl.AsyncRateLimitExecutor.lambda$execute$0(AsyncRateLimitExecutor.java:67)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
```

Looking at the code, it seems that the error was logged here:

https://github.com/slackapi/java-slack-sdk/blob/fa458c2f70524b41bd1a6e5014dc3b340f360e3e/slack-api-client/src/main/java/com/slack/api/methods/impl/TeamIdCache.java#L42-L45

`logger.error()` can trigger alerts in our system, so ideally we'd like to have this fixed. I tested sending a request to `https://slack.com/api/auth.test` and it indeeds return `invalid_auth`, which indicates that `auth.test` doesn't support OIDC access token:

```
{
    "ok": false,
    "error": "invalid_auth"
}
```

**Comment by seratch** [comment]
Hi @erathorus, thanks for taking the time to report this issue! I will submit a pull request to fix this shortly. Also, the change will be included in the next release (we're aiming to ship it next week).
